# Copyright (C) 2026 ren-yamanashi
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2.0,
# as published by the Free Software Foundation.
#
# This program is designed to work with certain software (including
# but not limited to OpenSSL) that is licensed under separate terms,
# as designated in a particular file or component or in included license
# documentation. The authors of this program hereby grant you an additional
# permission to link the program and your derivative works with the
# separately licensed software that they have either included with
# the program or referenced in the documentation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.

# mysqld side of the sysbench harness. Plugin baked from the e2e
# Dockerfile's `builder` stage (Makefile builds and tags
# `rusty-plugin-build:local` first). sysbench / jq / python3 live in
# the sibling `Dockerfile.client` so the EPEL drift problem of the
# Oracle Linux base stays out of the published measurements.

FROM rusty-plugin-build:local AS plugin

FROM mysql:8.4.9

COPY --from=plugin \
     /workspace/target/release/libengine.so \
     /usr/lib64/mysql/plugin/ha_rusty.so
