// Copyright (C) 2026 ren-yamanashi
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License, version 2.0,
// as published by the Free Software Foundation.
//
// This program is designed to work with certain software (including
// but not limited to OpenSSL) that is licensed under separate terms,
// as designated in a particular file or component or in included license
// documentation. The authors of this program hereby grant you an additional
// permission to link the program and your derivative works with the
// separately licensed software that they have either included with
// the program or referenced in the documentation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, see <https://www.gnu.org/licenses/>.

// Generated by bindgen via `make sys-bindings`. Do not edit by hand.

/* automatically generated by rust-bindgen 0.71.1 */

pub const HA_ERR_FIRST: i32 = 120;
pub const HA_ERR_KEY_NOT_FOUND: i32 = 120;
pub const HA_ERR_FOUND_DUPP_KEY: i32 = 121;
pub const HA_ERR_INTERNAL_ERROR: i32 = 122;
pub const HA_ERR_RECORD_CHANGED: i32 = 123;
pub const HA_ERR_WRONG_INDEX: i32 = 124;
pub const HA_ERR_ROLLED_BACK: i32 = 125;
pub const HA_ERR_CRASHED: i32 = 126;
pub const HA_ERR_WRONG_IN_RECORD: i32 = 127;
pub const HA_ERR_OUT_OF_MEM: i32 = 128;
pub const HA_ERR_NOT_A_TABLE: i32 = 130;
pub const HA_ERR_WRONG_COMMAND: i32 = 131;
pub const HA_ERR_OLD_FILE: i32 = 132;
pub const HA_ERR_NO_ACTIVE_RECORD: i32 = 133;
pub const HA_ERR_RECORD_DELETED: i32 = 134;
pub const HA_ERR_RECORD_FILE_FULL: i32 = 135;
pub const HA_ERR_INDEX_FILE_FULL: i32 = 136;
pub const HA_ERR_END_OF_FILE: i32 = 137;
pub const HA_ERR_UNSUPPORTED: i32 = 138;
pub const HA_ERR_TOO_BIG_ROW: i32 = 139;
pub const HA_ERR_FOUND_DUPP_UNIQUE: i32 = 141;
pub const HA_ERR_UNKNOWN_CHARSET: i32 = 142;
pub const HA_ERR_WRONG_MRG_TABLE_DEF: i32 = 143;
pub const HA_ERR_CRASHED_ON_REPAIR: i32 = 144;
pub const HA_ERR_CRASHED_ON_USAGE: i32 = 145;
pub const HA_ERR_LOCK_WAIT_TIMEOUT: i32 = 146;
pub const HA_ERR_LOCK_TABLE_FULL: i32 = 147;
pub const HA_ERR_READ_ONLY_TRANSACTION: i32 = 148;
pub const HA_ERR_LOCK_DEADLOCK: i32 = 149;
pub const HA_ERR_CANNOT_ADD_FOREIGN: i32 = 150;
pub const HA_ERR_NO_REFERENCED_ROW: i32 = 151;
pub const HA_ERR_ROW_IS_REFERENCED: i32 = 152;
pub const HA_ERR_NO_SAVEPOINT: i32 = 153;
pub const HA_ERR_NON_UNIQUE_BLOCK_SIZE: i32 = 154;
pub const HA_ERR_NO_SUCH_TABLE: i32 = 155;
pub const HA_ERR_TABLE_EXIST: i32 = 156;
pub const HA_ERR_NO_CONNECTION: i32 = 157;
pub const HA_ERR_NULL_IN_SPATIAL: i32 = 158;
pub const HA_ERR_TABLE_DEF_CHANGED: i32 = 159;
pub const HA_ERR_NO_PARTITION_FOUND: i32 = 160;
pub const HA_ERR_RBR_LOGGING_FAILED: i32 = 161;
pub const HA_ERR_DROP_INDEX_FK: i32 = 162;
pub const HA_ERR_FOREIGN_DUPLICATE_KEY: i32 = 163;
pub const HA_ERR_TABLE_NEEDS_UPGRADE: i32 = 164;
pub const HA_ERR_TABLE_READONLY: i32 = 165;
pub const HA_ERR_AUTOINC_READ_FAILED: i32 = 166;
pub const HA_ERR_AUTOINC_ERANGE: i32 = 167;
pub const HA_ERR_GENERIC: i32 = 168;
pub const HA_ERR_RECORD_IS_THE_SAME: i32 = 169;
pub const HA_ERR_LOGGING_IMPOSSIBLE: i32 = 170;
pub const HA_ERR_CORRUPT_EVENT: i32 = 171;
pub const HA_ERR_NEW_FILE: i32 = 172;
pub const HA_ERR_ROWS_EVENT_APPLY: i32 = 173;
pub const HA_ERR_INITIALIZATION: i32 = 174;
pub const HA_ERR_FILE_TOO_SHORT: i32 = 175;
pub const HA_ERR_WRONG_CRC: i32 = 176;
pub const HA_ERR_TOO_MANY_CONCURRENT_TRXS: i32 = 177;
pub const HA_ERR_NOT_IN_LOCK_PARTITIONS: i32 = 178;
pub const HA_ERR_INDEX_COL_TOO_LONG: i32 = 179;
pub const HA_ERR_INDEX_CORRUPT: i32 = 180;
pub const HA_ERR_UNDO_REC_TOO_BIG: i32 = 181;
pub const HA_ERR_TABLE_IN_FK_CHECK: i32 = 183;
pub const HA_ERR_TABLESPACE_EXISTS: i32 = 184;
pub const HA_ERR_TOO_MANY_FIELDS: i32 = 185;
pub const HA_ERR_ROW_IN_WRONG_PARTITION: i32 = 186;
pub const HA_ERR_INNODB_READ_ONLY: i32 = 187;
pub const HA_ERR_FTS_EXCEED_RESULT_CACHE_LIMIT: i32 = 188;
pub const HA_ERR_TEMP_FILE_WRITE_FAILURE: i32 = 189;
pub const HA_ERR_INNODB_FORCED_RECOVERY: i32 = 190;
pub const HA_ERR_FTS_TOO_MANY_WORDS_IN_PHRASE: i32 = 191;
pub const HA_ERR_FK_DEPTH_EXCEEDED: i32 = 192;
pub const HA_ERR_SE_OUT_OF_MEMORY: i32 = 194;
pub const HA_ERR_TABLE_CORRUPT: i32 = 195;
pub const HA_ERR_QUERY_INTERRUPTED: i32 = 196;
pub const HA_ERR_TABLESPACE_MISSING: i32 = 197;
pub const HA_ERR_TABLESPACE_IS_NOT_EMPTY: i32 = 198;
pub const HA_ERR_WRONG_FILE_NAME: i32 = 199;
pub const HA_ERR_NOT_ALLOWED_COMMAND: i32 = 200;
pub const HA_ERR_COMPUTE_FAILED: i32 = 201;
pub const HA_ERR_ROW_FORMAT_CHANGED: i32 = 202;
pub const HA_ERR_NO_WAIT_LOCK: i32 = 203;
pub const HA_ERR_DISK_FULL_NOWAIT: i32 = 204;
pub const HA_ERR_NO_SESSION_TEMP: i32 = 205;
pub const HA_ERR_WRONG_TABLE_NAME: i32 = 206;
pub const HA_ERR_TOO_LONG_PATH: i32 = 207;
pub const HA_ERR_SAMPLING_INIT_FAILED: i32 = 208;
pub const HA_ERR_FTS_TOO_MANY_NESTED_EXP: i32 = 209;
pub const HA_ERR_LAST: i32 = 209;
pub const HA_ERR_ERRORS: i32 = 90;
pub type Table_flags = ::std::os::raw::c_ulonglong;
#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum thr_lock_type {
  TL_IGNORE = -1,
  TL_UNLOCK = 0,
  TL_READ_DEFAULT = 1,
  TL_READ = 2,
  TL_READ_WITH_SHARED_LOCKS = 3,
  TL_READ_HIGH_PRIORITY = 4,
  TL_READ_NO_INSERT = 5,
  TL_WRITE_ALLOW_WRITE = 6,
  TL_WRITE_CONCURRENT_DEFAULT = 7,
  TL_WRITE_CONCURRENT_INSERT = 8,
  TL_WRITE_DEFAULT = 9,
  TL_WRITE_LOW_PRIORITY = 10,
  TL_WRITE = 11,
  TL_WRITE_ONLY = 12,
}
